module.exports = {
	READY: 'READY',
	METADATA_LOADED: 'METADATA_LOADED',
	PLAY: 'PLAY',
	PAUSE: 'PAUSE',
	END: 'END',
	PROGRESS_Q1: 'PROGRESS_Q1',
	PROGRESS_Q2: 'PROGRESS_Q2',
	PROGRESS_Q3: 'PROGRESS_Q3',
	PROGRESS_Q4: 'PROGRESS_Q4',
	ENTER_FULLSCREEN: 'ENTER_FULLSCREEN',
	EXIT_FULLSCREEN: 'EXIT_FULLSCREEN',
	ERROR: 'ERROR',
	IMPRESSION: 'IMPRESSION',
	VIEW: 'VIEW',
	BUFFERING_STARTED: 'BUFFERING_STARTED',
	BUFFERING_COMPLETED: 'BUFFERING_COMPLETED'
};