module.exports = {
	ON_READY: 'ON_READY',
	ON_METADATA_LOADED: 'ON_METADATA_LOADED',
	ON_PLAY: 'ON_PLAY',
	ON_PAUSE: 'ON_PAUSE',
	ON_END: 'ON_END',
	ON_PROGRESS_Q1: 'ON_PROGRESS_Q1',
	ON_PROGRESS_Q2: 'ON_PROGRESS_Q2',
	ON_PROGRESS_Q3: 'ON_PROGRESS_Q3',
	ON_PROGRESS_Q4: 'ON_PROGRESS_Q4',
	ON_ENTER_FULLSCREEN: 'ON_ENTER_FULLSCREEN',
	ON_EXIT_FULLSCREEN: 'ON_EXIT_FULLSCREEN',
	ON_ERROR: 'ON_ERROR',
	ON_IMPRESSION: 'ON_IMPRESSION',
	ON_VIEW: 'ON_VIEW'
};